[theme]
base = "light"
# HRMS palette (light)
primaryColor = "#2563EB"                # Indigo 600
backgroundColor = "#F7F9FC"             # Very light slate
secondaryBackgroundColor = "#FFFFFF"    # White cards
textColor = "#0F172A"                   # Slate-900
font = "Inter"
