[theme]
base = "light"
primaryColor = "#2E5AAC"              # HRMS blue
backgroundColor = "#F7FAFC"           # app background
secondaryBackgroundColor = "#FFFFFF"  # cards/panels
textColor = "#0F172A"                 # slate-900
font = "Inter"
